# Generated by Django 3.0.7 on 2020-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manu',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='manu',
            name='query',
            field=models.TextField(blank=True),
        ),
    ]
